export const lunchDishes = [
    "Couscous chana salad",
    "Lassagna",
    "Sabudana",
    "Tacos",
    "Egg curry",
    "Grilled chicken veggies",
    "Gobhi aloo raita",
    "Spinach Thhecha Rice",
    "Orzo salad",
    "Tomato soup",
    "Minestrone soup",
    "Brocolli soup",
    "Paneer kulcha",
    "Smashed potatoes salad",
    "Brussel Sprouts salad",
    "Aglio e olio",
    "Chilli Soya and Fried Rice",
    "Katsu curry",
    "Pasta Salad",
    "Mushroom / White Sauce Pasta",
    "Noodles",
    "Peri peri chicken/ paneer bowl",
    "Shakshouka",
    "Chicken breast with veggies",
    "Caesar salad",
    "Khichdi",
    "Chicken Curry & Roti",
    "Egg curry & Roti",
    "Paneer Bhurji",
    "Palak Paneer",
    "Aloo Gobhi Raita",
    "Bhindi Raita & Roti",
    "Cholle & Rice",
    "Rajma & Rice"
];

export const dinnerDishes = [
    "Couscous chana salad",
    "Lassagna",
    "Sabudana",
    "Tacos",
    "Egg curry",
    "Grilled chicken veggies",
    "Gobhi aloo raita",
    "Spinach Thhecha Rice",
    "Orzo salad",
    "Tomato soup",
    "Minestrone soup",
    "Brocolli soup",
    "Paneer kulcha",
    "Smashed potatoes salad",
    "Brussel Sprouts salad",
    "Aglio e olio",
    "Chilli Soya and Fried Rice",
    "Katsu curry",
    "Pasta Salad",
    "Mushroom / White Sauce Pasta",
    "Noodles",
    "Peri peri chicken/ paneer bowl",
    "Shakshouka",
    "Chicken breast with veggies",
    "Caesar salad",
    "Khichdi",
    "Chicken Curry & Roti",
    "Egg curry & Roti",
    "Paneer Bhurji",
    "Palak Paneer",
    "Aloo Gobhi Raita",
    "Bhindi Raita & Roti",
    "Cholle & Rice",
    "Rajma & Rice"
];
